### ISSUE TITLE
shell启动方式，重启Linux后jdbase定时任务不生效？

### ISSUE THREAD

**Issue by 365360171** [RikudouPatrickstar/jd-base#10]
crontab -l 查看了是crontab.list的内容
手动crontab crontab.list不起作用

**Comment by 365360171** [comment]
手动任务运行jd_xxx任务可以执行

**Comment by RikudouPatrickstar** [comment]
什么操作系统？什么叫 “手动crontab crontab.list不起作用”？确认过 crontab 相关服务的开机启动状态了吗？

**Comment by 365360171** [comment]
> 什么操作系统？什么叫 “手动crontab crontab.list不起作用”？确认过 crontab 相关服务的开机启动状态了吗？

termux
安装termux-services后，重启termux
启动crond服务：sv-enable crond
应该可以用了。
瞎折腾😂，感谢大佬指点
