### ISSUE TITLE
美丽研究院出bug了

### ISSUE THREAD

**Issue by SuperZhanggy** [RikudouPatrickstar/jd-base#11]
![image](https://user-images.githubusercontent.com/50569825/109601024-23ed6b80-7b59-11eb-865b-8eec44115e40.png)

**Comment by RikudouPatrickstar** [comment]
@SuperZhanggy js 脚本的问题怎么来这提 issue 啊？你看我的 jd-base 这个项目里面有这个脚本不

**Comment by SuperZhanggy** [comment]
不好意思，我以为是同一个人开发的

**Comment by RikudouPatrickstar** [comment]
@SuperZhanggy 那是 lxk0301 开发维护的，jd-base 只是套壳工具
