### ISSUE TITLE
导出互助码格式

### ISSUE THREAD

**Issue by leeyiding** [RikudouPatrickstar/jd-base#12]
每次手动倒腾互助太添麻烦了，能否能导出适用于配置文件的互助码格式
类似于如下这样的格式
```
MyFruit1="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MyFruit2="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MyFruit3="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MyFruit4="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MyFruit5="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ForOtherFruit1="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
ForOtherFruit2="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
ForOtherFruit3="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
ForOtherFruit4="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
ForOtherFruit5="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
```

**Comment by RikudouPatrickstar** [comment]
@leeyiding 你是说重新安装 jd-base 保留配置文件吗？

**Comment by leeyiding** [comment]
> @leeyiding 你是说重新安装 jd-base 保留配置文件吗？

不是，是`export_sharecodes.sh`这个脚本导出互助码的格式

**Comment by RikudouPatrickstar** [comment]
```
MyFruit1="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MyFruit2="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MyFruit3="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MyFruit4="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MyFruit5="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```
上面这一部分实现起来没什么问题，唯一担心的就是如果 cookie 有变化，比如调换了位置、删除了一个账号，这样导出的互助码就不会和 cookie 一一对应。而下面这一部分账号之间怎么助力的话，这个就不太好直接定义死了
```
ForOtherFruit1="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
ForOtherFruit2="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
ForOtherFruit3="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
ForOtherFruit4="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
ForOtherFruit5="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
```

**Comment by RikudouPatrickstar** [comment]
你嫌麻烦的应该是下面这一部分吧（我也觉得麻烦），也想过要调整这里，不过没思路怎么去弄，你有什么建议吗？

**Comment by Rainnnray** [comment]
可以定义jd.sh文件## 组合 Cookie、Token 与互助码
执行脚本会优先助力config.sh里面的互助码，其次就会执行jd.sh里面的互助码
例如互助东东农场：
export FRUITSHARECODES=$(Combin_Sub ForOtherFruit "xxxxxxxxxxxxxxxxxx&xxxxxxxxxxxxxxxxxx&xxxxxxxxxxxxxxxxxx")
执行东东农场脚本就会次于config.sh互助码后，执行该内容互助码

**Comment by RikudouPatrickstar** [comment]
@Rainnnray 额，你在说啥

**Comment by Rainnnray** [comment]
> @Rainnnray 额，你在说啥

就是定义jd.sh里面的export
![image](https://user-images.githubusercontent.com/33573345/109803315-defe2d80-7c5b-11eb-9cd1-ae5f8337bdeb.png)

**Comment by RikudouPatrickstar** [comment]
@Rainnnray 这一部分我是故意干掉的，我写在这里的话，会强迫所有人助力，脚本使用者写在这里的话，会被 git_pull.sh 干掉的。

**Comment by Rainnnray** [comment]
@RikudouPatrickstar 或者另外写一个脚本，将日志中的互助码提取写入jd.sh，在跑完git_pull.sh之后执行，不知道能否实现？

就是因为互助这个太麻烦，想借大佬您的库自建一个库自用来着，奈何不太会搞不定哈哈哈~

**Comment by RikudouPatrickstar** [comment]
@Rainnnray 就是提取完互助码直接全部拼接到一起，完全不给自定义的机会，被助力就是越前面的账号优先级越高这样子？

**Comment by leeyiding** [comment]
@Rainnnray 感觉你说的完全没有必要，自动提取互助码写入文件的话会有很多不确定因素
建议第一次部署脚本以后就等待一天或者手动运行需要助力码的脚本，然后直接从`export_sharecodes.sh`导出的互助码复制粘贴到config.sh就行了，如果还想为Cookie列表外的人互助，手动在后面添加变量就行了。部署完成后就尽量不要随意增删Cookie顺序了

**Comment by Rainnnray** [comment]
@RikudouPatrickstar 是的，这样也会一个账号助力完接着助力下一个，越前面的账号优先级越高，就不存在cookie 的顺序变化影响助力了，也不必麻烦去写各个账号的互助~

**Comment by RikudouPatrickstar** [comment]
@Rainnnray 要不受 cookie 顺序影响的话，就得运行脚本之前临时提取互助码了，不能从日志提。得去研究下每个活动分别具体是怎么和京东那边交互获取互助码的，原来的活动有什么变化或者新增了活动的话又得去弄。一想到这，一点动力都没有了，哈哈哈

**Comment by leeyiding** [comment]
我有个想法  就是导出互助码的话先执行一遍js库里的`jd_get_share_code.js`从日志里提取出长期活动的助力码，短期活动的话还是少数，可以先运行一遍相应活动的脚本，然后从运行运行日志提取短期活动助力码。这样的话能保证增删Cookie后，能在较短的时间内导出所有活动的助力码。

**Comment by RikudouPatrickstar** [comment]
@leeyiding 就是不直接集成到jd.sh了，继续改造export_sharecodes.sh？不过运行这部分脚本，账号稍微多点的话还是要等挺久的。

**Comment by leeyiding** [comment]
@RikudouPatrickstar 目前`jd_get_share_code.js`没有集成口袋书店和签到领现金两个脚本的互助码，这两个脚本十个账号以内的话运行总时间不会超过10分钟的，毕竟很多账号都没有开通口袋书店，而且签到领现金的任务也不多。更换Cookie后先手动运行一遍临时任务脚本，再运行导出互助码脚本，基本上也不会耗时太久的。

**Comment by tengqian** [comment]
大佬，弱弱的问一句为啥把`diy.sh`给干掉了，感觉挺有用的，可以插入些其他大佬的代码。 @RikudouPatrickstar

**Comment by RikudouPatrickstar** [comment]
@tengqian 就感觉 diy.sh 挺多余的，需要干别的事的话，自己额外撸一个脚本再加定时任务不就好了吗？（ps：有新的问题不该新开一个 issue 吗）

**Comment by RikudouPatrickstar** [comment]
@leeyiding lxk0301把签到领现金加上了，口袋书店的脚本挂了，估计在修。等那边做好在格外写个脚本直接从 jd_get_share_code.js 提取好了，临时活动还是用 export_sharecodes.sh 从日志提取。

**Comment by xxp2277** [comment]
@RikudouPatrickstar 作者你好，感谢你的辛苦工作。这个项目很好，学习难度很低，小白的我也弄成功了。
关于互助码的问题有两个建议：1 像leeyiding所说，从日志里提取出长期活动的助力码之后，能否更傻瓜化一点，自动写入到jd.sh中，而不必手动复制粘贴？（或者另外弄个临时文件单独保存这些内部帐号的互助码，每隔一天提取日志中的信息进行更新？）；2 互助码共享池有点不好上车，楼主有考虑新建一个么？

**Comment by RikudouPatrickstar** [comment]
@xxp2277 
1. 互助码不必手动复制粘贴，只助力自己提供的账号，这个功能 evine 已经做了部分了，效果类似 ”统一优先级助力”。下回有空的话我给加几个花样吧。
2. 共享池我暂时就不打算建了，这个要承担服务器费用，还要花时间维护，很佩服那位建共享池的同学。

**Comment by xxp2277** [comment]
> 
> 
> @xxp2277
> 
>     1. 互助码不必手动复制粘贴，只助力自己提供的账号，这个功能 evine 已经做了部分了，效果类似 ”统一优先级助力”。下回有空的话我给加几个花样吧。
> 
>     2. 共享池我暂时就不打算建了，这个要承担服务器费用，还要花时间维护，很佩服那位建共享池的同学。

1、好的，期待你的后续更新。我今天还手动将导出的互助码填写到config.sh里去了，看来是多此一举了，需要将其删除么？
2、共享池要服务器就算了，我以为靠tg自带的功能就能提供了呢。

**Comment by RikudouPatrickstar** [comment]
@xxp2277 暂时别删除，那个功能我还没加，[SuperManito](https://github.com/SuperManito/JD-FreeFuck/blob/source/jd.sh#L55) 那边已经支持了，你也可以先用他的

**Comment by RikudouPatrickstar** [comment]
@xxp2277 记错了，(尴尬.jpg)，他们只是 ForOther 变量不要填，My 变量还是要填，等待开发吧

**Comment by RikudouPatrickstar** [comment]
@xxp2277 别删，那个功能完成度还很低，我这里也完全没做支持，后续可能咕咕咕。
