### ISSUE TITLE
请教UA如何填写

### ISSUE THREAD

**Issue by dudt** [RikudouPatrickstar/jd-base#15]
![image](https://user-images.githubusercontent.com/19968269/110206361-23860500-7eb8-11eb-834a-1ec849d06d11.png)
这里也没有参考格式~~

**Comment by RikudouPatrickstar** [comment]
"不了解 User-Agent 的请不要随意填写内容"

**Comment by dudt** [comment]
> “不了解User-Agent的请不要随意填写内容”

我需要他啊,所以求一个格式..

**Comment by RikudouPatrickstar** [comment]
@Mabisi 你是已经填了一个京东的 UA 用不了吗？

**Comment by RikudouPatrickstar** [comment]
@Mabisi 这个得自己从京东APP抓包获取啊

**Comment by dudt** [comment]
> @Mabisi 这个得自己从京东APP抓包获取啊

没有填UA..大佬可以给个格式嘛，我好知道抓哪些

**Comment by RikudouPatrickstar** [comment]
@Mabisi 哪有什么格式，抓到什么就是什么呗。干嘛非要自己填这个？

**Comment by RikudouPatrickstar** [comment]
@Mabisi 你确定你知道 UA 是个什么吗？

**Comment by RikudouPatrickstar** [comment]
@Mabisi HTTP 请求头里面，这种样子：
![屏幕截图 2021-03-06 212537](https://user-images.githubusercontent.com/68163551/110208184-9300f200-7ec2-11eb-9c5d-291ceea950dc.jpg)
