### ISSUE TITLE
请问为什么没有定时执行，按照readme来安装的

### ISSUE THREAD

**Issue by xulingran** [RikudouPatrickstar/jd-base#16]
手动运行会有日志，但是一直没有自动

**Comment by RikudouPatrickstar** [comment]
什么设备、操作系统？

**Comment by xulingran** [comment]
阿里云轻量 centos 7 ，之前用EvineDeng的docker也是正常的

**Comment by RikudouPatrickstar** [comment]
能说明一下，使用一键脚本，具体是如何操作的吗？我测试一下

**Comment by xulingran** [comment]
我在使用了readme里提供的代码后，在sh中把路径更改为/appdata/jd，其他都是回车保持默认

**Comment by xulingran** [comment]
全部以默认设置解决了，谢谢大佬

**Comment by RikudouPatrickstar** [comment]
这个不能换的，除非你直接把 Dockerfile 和 docker-entrypoint.sh 都改掉，自己构建镜像
