### ISSUE TITLE
Docker 镜像更换

### ISSUE THREAD

**Issue by RikudouPatrickstar** [RikudouPatrickstar/jd-base#17]
抱歉各位，不小心把两个 dockerhub 账号：[rikudoupatrickstar](https://hub.docker.com/r/rikudoupatrickstar/jd-base) [ohmypatrick](https://hub.docker.com/r/ohmypatrick/jd-base) 搞没了，弄不回来了，重新注册了个 [thisispatrick](https://hub.docker.com/r/thisispatrick/jd-base)，麻烦大家更换一下镜像

**Comment by iServes** [comment]
大佬能不能把仓库换成Gitee，国内拉取不了呀

**Comment by RikudouPatrickstar** [comment]
@iServes 是 Docker 镜像拉不动还是 git_pull.sh 更新代码更新不动呀？

**Comment by iServes** [comment]
> @iServes 是 Docker 镜像拉不动还是 git_pull.sh 更新代码更新不动呀？

github这边，docker这边其实我也拉不动，但是为了我能拉动 我用actions拉取后打包放到了阿里云上，所以docker镜像这边没事。
主要是github这边，不知道为啥腾讯轻量北京这边clone github代码没速度，根本clone不下来，所以希望把github换成码云仓库或者别的其他国内仓库

**Comment by iServes** [comment]
@RikudouPatrickstar  哈哈，大佬我解决了。

**Comment by RikudouPatrickstar** [comment]
@iServes 你干啥了？😂我还在纠结搞不搞 gitee 呢（主要是自己能从 github 和 dockerhub 拉东西，有点懒）

**Comment by Rainnnray** [comment]
@RikudouPatrickstar 大佬有空搞个gitee吧，我腾讯轻量直接拉不动

**Comment by RikudouPatrickstar** [comment]
@iServes @Rainnnray ，二位如果有空的话，麻烦在你们的环境上帮我测试下这两组镜像加速的拉取效果。感觉 gitee 太难用了😅

其他看到了这条消息的大家也欢迎测试反馈~

```shell
git clone -b master https://github.com.cnpmjs.org/RikudouPatrickstar/jd_scripts jd_scripts_cnpmjs
git clone -b v3 https://github.com.cnpmjs.org/RikudouPatrickstar/jd-base jd-base_cnpmjs
```
```shell
git clone -b master https://hub.fastgit.org/RikudouPatrickstar/jd_scripts jd_scripts_fastgit
git clone -b v3 https://hub.fastgit.org/RikudouPatrickstar/jd-base jd-base_fastgit
```

**Comment by Rainnnray** [comment]
@RikudouPatrickstar 
![Uploading 1F8D702E-DAA0-4DE8-AB52-404908587B3F.png…]()

**Comment by RikudouPatrickstar** [comment]
@Rainnnray 不好意思，是不是误操作了，这张图片我看不到啊

**Comment by Rainnnray** [comment]
@RikudouPatrickstar 
![CBFD001D-4873-4251-BC92-ED77104A81A6](https://user-images.githubusercontent.com/33573345/110316099-3417b600-8045-11eb-99f7-edf0250c4332.png)

**Comment by RikudouPatrickstar** [comment]
@Rainnnray 收到

**Comment by iServes** [comment]
> @iServes 你干啥了？😂我还在纠结搞不搞 gitee 呢（主要是自己能从 github 和 dockerhub 拉东西，有点懒）

我觉得你只要在actions任务上加一个推送到gitee就行了，lxk的代码就直接用它的仓库。
这样你只需要在这个仓库push的时候同步到gitee就可以了

**Comment by iServes** [comment]
我目前就是用actions把你的仓库拉下来，然后替换Dockerfile里的github链接为镜像链接。然后构建上传到我自己的容器仓库。然后自己用 🤭

**Comment by RikudouPatrickstar** [comment]
@iServes 我知道，就是觉得 gitee 用不惯，不想搞个 gitee 的库

**Comment by iServes** [comment]
> @iServes 我知道，就是觉得 gitee 用不惯，不想搞个 gitee 的库

哦哦，我其实也不用gitee ，我是把代码都同步到coding，然后拉取 😓 
![image](https://user-images.githubusercontent.com/67787455/110322337-f4090100-804d-11eb-9501-e57c39577ffa.png)

**Comment by RikudouPatrickstar** [comment]
镜像加速搞上了，git 用 github.com.cnpmjs.org 加速，wget 拉文件通过 cdn.jsdelivr.net。大家伙试试

**Comment by liaopen123** [comment]
感谢大佬  爱你
