### ISSUE TITLE
各位金融养猪脚本任务做不了是什么回事？

### ISSUE THREAD

**Issue by 365360171** [RikudouPatrickstar/jd-base#18]
![IMG_20210308_202139](https://user-images.githubusercontent.com/8091077/110320965-03874a80-804c-11eb-8f45-a5f7cea161a8.jpg)
很多浏览任务都是未完成

**Comment by RikudouPatrickstar** [comment]
https://gitee.com/lxk0301/jd_docker/issues
去这里反馈，谢谢

**Comment by 365360171** [comment]
> https://gitee.com/lxk0301/jd_docker/issues
> 去这里反馈，谢谢

已反馈。谢谢！
