### ISSUE TITLE
环球挑战赛任务运行失败

### ISSUE THREAD

**Issue by robin0409** [RikudouPatrickstar/jd-base#20]
日志如下：
----------
当前活动：第3/24天
去做每日签到任务
{"code":"1"}
您的好友助力码为 bmVYdkFBQlVQZzlVVGRSeFd2dXpadz09
去做去进口超市下单解锁奖励任务
{"code":"1"}
去做逛进口超市宠粉会场20秒任务
{"code":"1"}
去做浏览进口精选商品20秒任务
{"code":"1"}
{"code":"1"}
{"code":"1"}
{"code":"1"}
{"code":"1"}
去做逛惠氏营养品会场20秒任务
{"code":"1"}
{"code":"1"}
{"code":"1"}
{"code":"1"}
{"code":"1"}
{"code":"1"}
{"code":"1"}

==============📣系统通知📣==============
环球挑战赛
京东账号1wdnzvGVtbxHyya
本次运行获得0里程，0京豆，共计120里程
{"code":"1"}

🔔环球挑战赛, 结束! 🕛 20.248 秒

"Timeout awaiting 'request' for 10000ms"
环球挑战赛 API请求失败，请检查网路重试
----------

手机app上查看任务并没有完成

**Comment by RikudouPatrickstar** [comment]
https://gitee.com/lxk0301/jd_docker/issues
去这里反馈，谢谢
