### ISSUE TITLE
找不到config.sh.sample

### ISSUE THREAD

**Issue by zglzw** [RikudouPatrickstar/jd-base#22]
Bark推送有模板更新，但是在/root/jd-docker/config没有找到config.sh.sample文件，其他功能一切正常

**Comment by RikudouPatrickstar** [comment]
推送有告诉你 config.sh.sample 文件在 /root/jd-docker/config 目录下吗？

**Comment by zglzw** [comment]
> 推送有告诉你 config.sh.sample 文件在 /root/jd-docker/config 目录下吗？

我记得一直以来这个文件都是和config.sh在同一个文件夹里的😂今天发现没有了

**Comment by RikudouPatrickstar** [comment]
不用找了，web 面板不香吗🤪。我嫌在命令行里做对比太麻烦，移除了

**Comment by zglzw** [comment]
> 不用找了，web 面板不香吗🤪。我嫌在命令行里做对比太麻烦，移除了

好的谢谢大佬，我这就去用面板😂
