### ISSUE TITLE
无法访问web控制面板

### ISSUE THREAD

**Issue by BROBIRD** [RikudouPatrickstar/jd-base#23]
使用Docker部署
随机提示以下三种错误之一

0.Connection refused
1.Connection reset by peer
2.Empty reply from server

**Comment by RikudouPatrickstar** [comment]
@BROBIRD Docker？

**Comment by BROBIRD** [comment]
是的 使用Docker部署的，经过观察一段时间后似乎会直接进入重启中的状态

**Comment by RikudouPatrickstar** [comment]
@BROBIRD 好，我大概知道了，等会修一下

**Comment by BROBIRD** [comment]
@RikudouPatrickstar 这就是大佬的速度吗（我这边随时可以帮忙测试

**Comment by RikudouPatrickstar** [comment]
@BROBIRD 修完了，试一下

**Comment by BROBIRD** [comment]
可以了，感谢及时修复
