### ISSUE TITLE
Panel服务挂了，起不来

### ISSUE THREAD

**Issue by Jesn** [RikudouPatrickstar/jd-base#24]
```
/root/.pm2/logs/server-error.log last 15 lines:
0|server   | Require stack:
0|server   | - /jd/panel/server.js
0|server   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
0|server   |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|server   |     at require (internal/modules/cjs/helpers.js:88:18)
0|server   |     at Object.<anonymous> (/jd/panel/server.js:11:19)
0|server   |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|server   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
0|server   |     at Module.load (internal/modules/cjs/loader.js:928:32)
0|server   |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
0|server   |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|server   |     at Module._compile (internal/modules/cjs/loader.js:1063:30) {
0|server   |   code: 'MODULE_NOT_FOUND',
0|server   |   requireStack: [ '/jd/panel/server.js' ]
0|server   | }
```

**Comment by RikudouPatrickstar** [comment]
最新的镜像吗

**Comment by Jesn** [comment]
> 最新的镜像吗

是的，我刚才在Windows Docker上测试是ok的，但是在Centos Stream 上的Docker运行就起不来，昨天我还可以打开面板，今天早上就打不开了

**Comment by RikudouPatrickstar** [comment]
CentOS7 上部署未发现问题，请删除本地镜像重新部署后再尝试。可能是这两天动了 docker-entrypoint 造成的

**Comment by Jesn** [comment]
我看你tag打成V3了，没有latest版了

**Comment by RikudouPatrickstar** [comment]
@Jesn tag 一直都是 v3，没搞过 latest 呀
https://hub.docker.com/r/thisispatrick/jd-base/tags

**Comment by Jesn** [comment]
我重新试了，还是报错，操作步骤如下：

1、清空了阿里云Docker加速器
2、拉取镜像 `docker pull ohmypatrick/jd-base:v3`
3、运行命令 `docker run -dit -p 5679:5678  --name jdV3   --restart always    ohmypatrick/jd-base:v3`
4、进入容器 `docker exec -it jdV3 bash`
5、`pm2 list`查看挂载服务列表 Status状态为errored

**Comment by RikudouPatrickstar** [comment]
@Jesn 我不是发置顶 issue 说换镜像了吗。。。现在是 thisispatrick/jd-base:v3

**Comment by Jesn** [comment]
不好意思，这个没看到，刚才使用  thisispatrick/jd-base:v3 镜像还是报同样的错误

**Comment by Jesn** [comment]
我进入到panel目录把`node_modules/`删除，然后重新`npm install`，重新加入到pm2，就好了

**Comment by anke1938** [comment]
大概率就是网络不好  node 的依赖没安全

**Comment by Jesn** [comment]
不应该每次都是这样，但是我手动执行就好了，反正目前这个问题已经能暂时解决掉

**Comment by RikudouPatrickstar** [comment]
@Jesn 可能是楼上 @anke1938 说的网络问题吧
![123](https://user-images.githubusercontent.com/68163551/110921090-202bc700-8359-11eb-93fa-386caacad564.jpg)
![456](https://user-images.githubusercontent.com/68163551/110921105-24f07b00-8359-11eb-9612-7569b6808231.jpg)

我测了还是没问题，哈哈

**Comment by Jesn** [comment]
嗯 ，那有可能，以后如果遇到类似的问题，就知道怎么处理了，谢谢 @RikudouPatrickstar @anke1938

**Comment by RikudouPatrickstar** [comment]
@Jesn 我刚改成优先使用淘宝源了，有空试下是否仍存在这个问题
