### ISSUE TITLE
计划任务不启动,手动运行脚本没有问题

### ISSUE THREAD

**Issue by cheninaisino** [RikudouPatrickstar/jd-base#26]
arm64的docker
镜像是thisispatrick/jd-base:v3
crontab -l里面是正常的

root@jd:/jd $ crontab -l
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

55 8-23/3 * * * bash /jd/git_pull.sh >> /jd/log/git_pull.log 2>&1
57 3 * * * bash /jd/rm_log.sh >/dev/null 2>&1
48 4 * * * bash /jd/export_sharecodes.sh
33 13 * * * bash /jd/jd.sh hangup

5 0 * * * bash /jd/jd.sh jd_bean_change
33 4 * * * bash /jd/jd.sh jd_bean_home
3 0,18 * * * bash /jd/jd.sh jd_bean_sign
0,30 0 * * * bash /jd/jd.sh jd_blueCoin
7 8,12,18 * * * bash /jd/jd.sh jd_bookshop
0 0 * * * bash /jd/jd.sh jd_car
0 0 * * * bash /jd/jd.sh jd_car_exchange
27 */4 * * * bash /jd/jd.sh jd_cash
5 0,8,13,19 * * * bash /jd/jd.sh jd_cfd
0 0 * * * bash /jd/jd.sh jd_club_lottery
10 7,23 * * * bash /jd/jd.sh jd_crazy_joy
10 12 * * * bash /jd/jd.sh jd_crazy_joy_bonus
18 * * * * bash /jd/jd.sh jd_daily_egg
20 9 * * 6 bash /jd/jd.sh jd_delCoupon
20 * * * * bash /jd/jd.sh jd_dreamFactory
*/20 * * * * bash /jd/jd.sh jd_family
5 6-18/6 * * * bash /jd/jd.sh jd_fruit
47 7 * * * bash /jd/jd.sh jd_get_share_code
36 * * * * bash /jd/jd.sh jd_jdfactory
10 11 * * * bash /jd/jd.sh jd_jdzz
45 */2,23 * * * bash /jd/jd.sh jd_joy
15 */1 * * * bash /jd/jd.sh jd_joy_feedPets
0 0-16/8 * * * bash /jd/jd.sh jd_joy_reward
10 9-20/2 * * * bash /jd/jd.sh jd_joy_run
0 0-10/2 * * * bash /jd/jd.sh jd_joy_steal
20 5,23 * * * bash /jd/jd.sh jd_jxd
0 9,12,18 * * * bash /jd/jd.sh jd_jxnc
23 1 * * * bash /jd/jd.sh jd_kd
10-20/5 12,23 * * * bash /jd/jd.sh jd_live
11 1 * * * bash /jd/jd.sh jd_lotteryMachine
0 */2 * * * bash /jd/jd.sh jd_moneyTree
10 7 * * * bash /jd/jd.sh jd_ms
20 0,20 * * * bash /jd/jd.sh jd_necklace
5 6-18/6 * * * bash /jd/jd.sh jd_pet
12 * * * * bash /jd/jd.sh jd_pigPet
0 7-22/1 * * * bash /jd/jd.sh jd_plantBean
1 0,23 * * * bash /jd/jd.sh jd_price
11 9 * * * bash /jd/jd.sh jd_rankingList
1 1 * * * bash /jd/jd.sh jd_redPacket
27 8 * * * bash /jd/jd.sh jd_sgmh
10 0 * * * bash /jd/jd.sh jd_shop
16 6,23 * * * bash /jd/jd.sh jd_small_home
8 */3 * * * bash /jd/jd.sh jd_speed
1 1,6 * * * bash /jd/jd.sh jd_speed_sign
11 1-23/5 * * * bash /jd/jd.sh jd_superMarket
36 8,18 * * * bash /jd/jd.sh jd_syj
55 23 * * * bash /jd/jd.sh jd_unsubscribe
39 7 * * * bash /jd/jd.sh jx_sign
 以下为自动添加的任务
5 1,23 * * * bash /jd/jd.sh jd_nzmh
15 0,23 * * * bash /jd/jd.sh jd_speed_redpocke
30,31 20-23/1 * * * bash /jd/jd.sh jd_live_redrain
1 7,12,19 * * * bash /jd/jd.sh jd_beauty
35 6,22 * * * bash /jd/jd.sh jd_global
5 7,12,23 * * * bash /jd/jd.sh jd_global_mh
0 0,12 * * * bash /jd/jd.sh jd_xtg
root@jd:/jd $ ps -ef|grep crond
 5772 root      0:00 crond start
 5774 root      0:00 crond status
 8433 root      0:00 grep crond

##root@jd:/jd $ ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 node
   17 root      0:00 bash
   22 root      0:00 bash
   62 root      7:19 {node} PM2 v4.5.5: God Daemon (/root/.pm2)
   73 root     24:00 node /jd/panel/server.js
 5772 root      0:00 crond start
 5774 root      0:00 crond status
 7947 root      0:00 bash /jd/jd.sh jd_jxnc
 7948 root      0:00 bash /jd/jd.sh jd_plantBean
 8144 root      0:04 node jd_plantBean.js
 8145 root      0:00 tee /jd/log/jd_plantBean/2021-03-18-09-00-00.log
 8147 root      0:04 node jd_jxnc.js
 8148 root      0:00 tee /jd/log/jd_jxnc/2021-03-18-09-00-00.log
 8164 root      0:00 bash /jd/jd.sh jd_jxnc
 8165 root      0:00 bash /jd/jd.sh jd_plantBean
 8364 root      0:04 node jd_plantBean.js
 8365 root      0:00 tee /jd/log/jd_plantBean/2021-03-18-09-00-01.log
 8373 root      0:04 node jd_jxnc.js
 8374 root      0:00 tee /jd/log/jd_jxnc/2021-03-18-09-00-01.log
 8392 root      0:08 node /jd/scripts/jd_crazy_joy_coin.js
 8426 root      0:00 bash
 8434 root      0:00 ps -ef

**Comment by RikudouPatrickstar** [comment]
？？？进程里面这些都是手动启动的？？？

**Comment by cheninaisino** [comment]
是的, node面板 挂机脚本 也是用pm命令手工启动的

**Comment by RikudouPatrickstar** [comment]
@cheninaisino 还有这种事，我晚上回来测测。你先本地生成镜像试试，看看会不会也这样

**Comment by cheninaisino** [comment]
好像我跑了crond start后计划任务好了?

**Comment by anke1938** [comment]
crontab 的日志有吗 .     多半是环境的问题

**Comment by RikudouPatrickstar** [comment]
ARM64 Docker 里面确实存在这个问题，昨天用华为云意外复现，我有空再看吧
