### ISSUE TITLE
docker-compose.yml的问题

### ISSUE THREAD

**Issue by kissfast** [RikudouPatrickstar/jd-base#27]
我看了大神仓库目录下的这个docker-compose.yml文件
有点不明白的地方
文件是定义了3个容器，也有不同的配置目录（除了log）之外
是不是要去3个容器里面修改保存了config文件后才可以执行？
这样能3个容器并发执行任务不？

**Comment by RikudouPatrickstar** [comment]
1. config 你共用一个也行，每个容器都配置一个也行，自己按需调整，docker-compose.yml 里面只是示例，随意写的。
2. config 目录及其内容的三个文件是这样的，相对 Evine 的仅做了一点点小调整。容器启动时，如果你从容器外部挂载了这些配置文件，那么采用你挂载的配置；如果没有挂载自己的配置，则默认将 sample 目录下的模板复制到 config 目录作为配置使用。

**Comment by kissfast** [comment]
明白了，谢谢。
