### ISSUE TITLE
京喜工厂太火爆的解决办法

### ISSUE THREAD

**Issue by robin0409** [RikudouPatrickstar/jd-base#28]
https://www.orzlee.com/web-development/2021/03/03/lxk0301-jingdong-signin-scriptjingxi-factory-solves-the-problem-of-unable-to-signin.html
docker方式的解决办法具体怎么操作呀
忘大佬指点一下，谢谢

**Comment by RikudouPatrickstar** [comment]
@robin0409 此 docker 非彼 docker，直接将你 改好的文件的 url 在 config.sh 填好就完事了

**Comment by robin0409** [comment]
就是不清楚加的位置，CUSTOM_SHELL_FILE 也是加这个参数？

**Comment by RikudouPatrickstar** [comment]
@robin0409 跟你说的这个环境变量没关系，jd-base 只是使用了 jd_scripts 的脚本而已。怎么填看配置文件，今天才更新

**Comment by robin0409** [comment]
好，我更新看下

**Comment by kissfast** [comment]
厉害，高手，膜拜
