### ISSUE TITLE
限制账号数量

### ISSUE THREAD

**Issue by SuperManito** [RikudouPatrickstar/jd-base#29]
## jd.sh

    ## 用户数量UserSum
    function Count_UserSum() {
      for ((i = 1; i <= 30; i++)); do
        Tmp=Cookie$i
        CookieTmp=${!Tmp}
        [[ ${CookieTmp} ]] && UserSum=$i || break
      done

      for ((d = 31; d <= 1000; d++)); do
        Del=Cookie$d
        sed -i "/${!Del}/d" ${FileConf} || break
      done
    }

**Comment by RikudouPatrickstar** [comment]
@SuperManito 好嘞，等会加上。直接删，真凶残🤪

**Comment by SuperManito** [comment]
> @SuperManito 好嘞，等会加上。直接删，真凶残🤪

没办法啊，哈哈哈，对付这群人我通知都不带发的，希望他们没有本地备份配置文件

**Comment by RikudouPatrickstar** [comment]
@SuperManito 哈哈哈，那怕不是会气死

**Comment by SuperManito** [comment]
> @SuperManito 哈哈哈，那怕不是会气死

本来我不想管的，有个人用我项目挂160个号我也是服了
![image](https://user-images.githubusercontent.com/68613938/111850819-3c78c680-894c-11eb-9d05-a7cbe74d2207.png)

**Comment by SuperManito** [comment]
@dockere

**Comment by RikudouPatrickstar** [comment]
@SuperManito 我天，160个号。拿开源项目这样子玩，太过分了吧，干死他

**Comment by SuperManito** [comment]
> @SuperManito 我天，160个号。拿开源项目这样子玩，太过分了吧，干死他

嗯
