### ISSUE TITLE
docker 镜像不存在啦么

### ISSUE THREAD

**Issue by anke1938** [RikudouPatrickstar/jd-base#3]
docker 镜像不存在啦么   pull不下来

Unable to find image 'patrick/jd-base:v3' locally
docker: Error response from daemon: repository patrick/jd-base not found: does not exist or no pull access

**Comment by RikudouPatrickstar** [comment]
对，不打算上传到 dockerhub，可以用 Dockerfile 在本地生成。也提供了 make-image 脚本方便生成镜像。

**Comment by RikudouPatrickstar** [comment]
不用 docker-compose 的话，推荐直接用一键脚本 https://github.com/RikudouPatrickstar/jd-base/raw/v3/docker/onekey-docker.sh

**Comment by RikudouPatrickstar** [comment]
不打算上传到 dockerhub，可以用 Dockerfile 在本地生成，相关流程脚本里面都做好了。你这个是手动 pull 报的错还是我的脚本报的错？

**Comment by anke1938** [comment]
一键脚本报错

**Comment by RikudouPatrickstar** [comment]
我这里测试没有问题呀。你是用的什么设备、操作系统？如何操作的？执行一键脚本过程中还有其他报错吗？

**Comment by anke1938** [comment]
![image](https://user-images.githubusercontent.com/26757566/108514704-251fcc80-72ff-11eb-83b6-2304756df984.png)

服务器环境:   BJ 阿里云    Ubuntu 16.04

之前也用你的脚本,一切正常

重新执行一键脚本是因为  16号开始   不执行任务   查看git_pull.log   发现找不到crontab  任务

你那里正常那我再找找原因    谢谢

**Comment by RikudouPatrickstar** [comment]
创建镜像的时候就出了问题，你再检查下，会不会是网络原因，比如：访问 github 有问题，在 git clone 的时候出错了。

**Comment by anke1938** [comment]
好的   应该是在clone 的时候错了   我去HK 的服务器试试  谢谢

**Comment by snakeJohn** [comment]
我也遇到了这个问题，重装系统后弄好的--，腾讯云服务器

**Comment by RikudouPatrickstar** [comment]
为了应对这种情况，已在 DockerHub 上传镜像，镜像名已更换为 ohmypatrick/jd-base:v3，已集成进一键脚本
