### ISSUE TITLE
更新脚本文件日志有点小问题 wget: missing URL

### ISSUE THREAD

**Issue by xxp2277** [RikudouPatrickstar/jd-base#30]
首先感谢作者的辛勤劳动！
手动更新脚本后，日志显示一个小错误。是因为没有需要替换的脚本，所以显示miss么？
日志如下：

##############################################################

系统时间：2021-03-20 16:59:46

--------------------------------------------------------------

更新 jd-base 脚本

Fetching origin
HEAD is now at bca36e8 增加临时活动“城城领现金”

更新 jd-base 脚本成功

--------------------------------------------------------------

更新 jd_scripts 脚本

Fetching origin
From https://github.com/RikudouPatrickstar/jd_scripts
   4142edb..ad110a6  master     -> origin/master
HEAD is now at ad110a6 add SCF tutorial image

更新 jd_scripts 脚本成功

--------------------------------------------------------------

替换 js 脚本

wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
.js 替换失败，请检查原因

--------------------------------------------------------------

设置额外的 js 脚本环境

**Comment by RikudouPatrickstar** [comment]
对，是因为没有需要替换的脚本，所以显示 wget 提示 miss URL，晚点加个判空

**Comment by RikudouPatrickstar** [comment]
@xxp2277 搞定，有空测一下

**Comment by xxp2277** [comment]
> 
> 
> @xxp2277 搞定，有空测一下

ok，没有问题了。
