### ISSUE TITLE
更新了脚本，但是还是获取不到互助码日志是哪里操作不对？

### ISSUE THREAD

**Issue by zekohung** [RikudouPatrickstar/jd-base#31]
也手动执行 git_pull.sh
例如：

## 城城领现金：
# 未从日志中匹配到任何互助码

**Comment by RikudouPatrickstar** [comment]
@zekohung 对，取不到，lxk0301 不按套路出牌。不想适配了，反正就几天的短期活动，你直接 log 里面动手复制吧

**Comment by zekohung** [comment]
> @zekohung对，取不到，lxk0301不按套路出牌。不想适应了，反正就几天的短期活动，你直接登录里面动手复制吧

好的，暂时也是自己手动匹配。
