### ISSUE TITLE
同步仓库

### ISSUE THREAD

**Issue by DoveBoy** [RikudouPatrickstar/jd-base#32]
不知道怎么联系你，只能用这个方式了，我知道你同步我的仓库，但是因为发现有人https://github.com/kddhi/akd同样同步我的仓库后用来跑ac，所以不得已把仓库私有了，所以对你也是误伤了。实在没办法

**Comment by RikudouPatrickstar** [comment]
@DoveBoy 
好的，感谢你还特地来告知我这个事情。我是中午发现你仓库的代码比 docker 镜像内置的代码更新，所以私自同步了你的仓库，如有冒犯，我给你道个歉，哈哈，当然我也希望能有方式继续获取到新的代码。我的 [TG](http://t.me/RikudouPatrickstar) 和 GitHub 同名，以后有什么事的话欢迎随时联系。

**Comment by xxp2277** [comment]
项目可惜了，未来不知道去哪里找类似的项目挂自己的两个帐号了。
