### ISSUE TITLE
关于在 ARM64 设备上执行 git_pull.sh 报类似错误或 Docker 容器不断重启

### ISSUE THREAD

**Issue by RikudouPatrickstar** [RikudouPatrickstar/jd-base#5]
在 ARM64 设备上执行 git_pull.sh 报类似错误或 Docker 容器不断重启，原因是 [jd_scripts](https://gitee.com/lxk0301/jd_scripts/tree/master/) 更新了相关依赖。已有[相关 PR](https://gitee.com/lxk0301/jd_scripts/pulls/180) 等待测试、合并。

**Comment by RikudouPatrickstar** [comment]
目前应该已经解决了

**Comment by kissfast** [comment]
我的docker正常了

**Comment by RikudouPatrickstar** [comment]
> 我的docker正常了

OK，那两个 PR 昨天晚上合并了🤪
