### ISSUE TITLE
仓库更新问题

### ISSUE THREAD

**Issue by zglzw** [RikudouPatrickstar/jd-base#6]
请问21号lxk0301大佬仓库私有化之后再使用一键脚本还可以正常安装使用并进行后续脚本更新吗？谢谢

**Comment by RikudouPatrickstar** [comment]
可以的，本项目所使用的 js 脚本是从我的镜像仓库拉取的。镜像仓库每天 8 点到 0 点每20分钟同步一次 
 lxk0301 大佬的私有仓库。

**Comment by zglzw** [comment]
> 可以的，本项目所使用的 js 脚本是从我的镜像仓库拉取的。镜像仓库每天 8 点到 0 点每20分钟同步一次
> lxk0301 大佬的私有仓库。

谢谢大佬我明白了，还有个问题就是用了docker的一键脚本后还用再安装containrrr/watchtower吗？手动更新脚本的命令是docker exec -it jd bash git_pull吗？

**Comment by RikudouPatrickstar** [comment]
containrrr/watchtower 可以不安装的(我自己就没装过🤪)，最近不打算调整 docker 的结构了，git_pull 就可以同步代码了。

**Comment by zglzw** [comment]
> containrrr/watchtower 可以不安装的(我自己就没装过🤪)，最近不打算调整 docker 的结构了，git_pull 就可以同步代码了。

好的多谢大佬

**Comment by zglzw** [comment]
另外大佬为什么用腾讯云5678端口安全组放行了并且关闭了防火墙也拒绝访问，而vultr的vps就没有这个问题

**Comment by RikudouPatrickstar** [comment]
没事，我只是个拿大佬东西修修改改的🥬🐔

**Comment by RikudouPatrickstar** [comment]
> 另外大佬为什么用腾讯云5678端口安全组放行了并且关闭了防火墙也拒绝访问，而vultr的vps就没有这个问题

我没用过腾讯☁️，没法解决你的问题，抱歉

**Comment by zglzw** [comment]
> > 另外大佬为什么用腾讯云5678端口安全组放行了并且关闭了防火墙也拒绝访问，而vultr的vps就没有这个问题
> 
> 我没用过腾讯☁️，没法解决你的问题，抱歉

好的谢谢大佬，那我再重装一遍试试

**Comment by Cevin-Yu** [comment]
> > > 另外大佬为什么用腾讯云5678端口安全组放行了并且关闭了防火墙也拒绝访问，而vultr的vps就没有这个问题
> > 
> > 
> > 我没用过腾讯cloud，没法解决你的问题，抱歉
> 
> 好的谢谢大佬，那我再重装一遍试试

5678我没搞定，我最后换成了80端口

**Comment by zglzw** [comment]
> > > > 另外大佬为什么用腾讯云5678端口安全组放行了并且关闭了防火墙也拒绝访问，而vultr的vps就没有这个问题
> > > 
> > > 
> > > 我没用过腾讯cloud，没法解决你的问题，抱歉
> > 
> > 
> > 好的谢谢大佬，那我再重装一遍试试
> 
> 5678我没搞定，我最后换成了80端口

好的谢谢大佬，我这就去试试
