### ISSUE TITLE
建议一件脚本的wget 加入   --no-check-certificate

### ISSUE THREAD

**Issue by anke1938** [RikudouPatrickstar/jd-base#7]
建议一件脚本的wget 加入   --no-check-certificate    

因为... 我服务器没有证书   而这种现象很常见...  导致下载的.sh 文件是空文件

**Comment by RikudouPatrickstar** [comment]
@anke1938 好的，还有这么一说呢，我考虑下

**Comment by RikudouPatrickstar** [comment]
@anke1938 想请教一下，是什么原因服务器上不安装证书呢？这个问题不是装一个就好了吗？使用 --no-check-certificate 会存在一定隐患的

**Comment by anke1938** [comment]
没什么原因...我就是懒....       这问题在我虚拟机  和 阿里云 HK 服务器出现   而阿里云  BJ服务器正常  但是 我丝毫不记得我操作过证书这种事情

**Comment by RikudouPatrickstar** [comment]
你还是取到脚本后自己改了再执行吧，哈哈
