### ISSUE TITLE
疯狂的joy挂机

### ISSUE THREAD

**Issue by zglzw** [RikudouPatrickstar/jd-base#8]
请问使用了docker一键脚本部署后应该如何启动挂机程序？cd 到脚本目录后输入 bash jd.sh hangup无效

**Comment by RikudouPatrickstar** [comment]
@zglzw 是这样执行的吗
docker exec -it jd bash jd.sh hangup

**Comment by zglzw** [comment]
> @zglzw 是这样执行的吗
> docker exec -it jd bash jd.sh hangup

感谢大佬，成功了

**Comment by zglzw** [comment]
还有大佬我根据这个命令输入了docker exec -it jd bash git_pull没手动更新脚本成功，提示bash: git_pull: No such file or directory

**Comment by RikudouPatrickstar** [comment]
@zglzw docker exec -it jd bash git_pull.sh

**Comment by zglzw** [comment]
> @zglzw docker exec -it jd bash git_pull.sh

感谢大佬
