### ISSUE TITLE
docker镜像源问题

### ISSUE THREAD

**Issue by zglzw** [RikudouPatrickstar/jd-base#9]
请问大佬有没有国内ecs服务器能用的docker加速源，用docker一键脚本在国内ecs服务器上拉取不动源码，网上找的好像都失效了，一点加速作用也没有。

**Comment by RikudouPatrickstar** [comment]
@zglzw 阿里的加速也不行吗？我是直接给系统配置代理了

**Comment by zglzw** [comment]
> @zglzw 阿里的加速也不行吗？我是直接给系统配置代理了

也不行，阿里腾讯百度七牛云都试了，速度极慢，有时还会断开连接，是不是我的ecs有问题

**Comment by RikudouPatrickstar** [comment]
@zglzw 你服务器的事我不清楚。不过你都上来 gayhub 了，给你服务器也配个代理呗

**Comment by zglzw** [comment]
> @zglzw 你服务器的事我不清楚。不过你都上来 gayhub 了，给你服务器也配个代理呗

我上gayhub是裸连2333。好的谢谢大佬，我去试试

**Comment by RikudouPatrickstar** [comment]
@zglzw 你自己加油搞吧。我这一半的 issue 都是你提的，而且都和代码没啥关系，都快不想看到你了，哈哈😅

**Comment by zglzw** [comment]
> @zglzw 你自己加油搞吧。我这一半的 issue 都是你提的，而且都和代码没啥关系，都快不想看到你了，哈哈😅

对不起大佬，我是个菜鸡，下次我尽量自己查资料解决，麻烦大佬了。
